image:
  file: .gitpod.Dockerfile

tasks:
  - name: Add marp-cli container
    init: docker pull marpteam/marp-cli
  - name: Add markdownlint container
    init: docker pull registry.gitlab.com/pipeline-components/markdownlint:latest
vscode:
  extensions:
   # Fix version to be compatible with current Gitpod workspace
   - marp-team.marp-vscode@2.1.0
  