gitlabUrl: https://gitlab.com/
runnerRegistrationToken: "glrt-hVyn7PXiAsuTos-3bR9q"
rbac:
  create: true
service:
  enabled: true
runners:
  privileged: true
  serviceAccountName: gitlab-runner
  config: |
    [[runners]]
      environment = [
        "DOCKER_HOST=tcp://docker:2376",
        "DOCKER_TLS_CERTDIR=/certs",
        "DOCKER_TLS_VERIFY=1",
        "DOCKER_CERT_PATH=$DOCKER_TLS_CERTDIR/client",
        "AWS_EC2_METADATA_DISABLED=true",
        "AWS_SDK_LOAD_CONFIG=true"
        ]
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "docker:19.03.12"
        privileged = true
        poll_timeout = 300
        poll_interval = 10
        cpu_request = "1"
        [[runners.kubernetes.volumes.empty_dir]]
          name = "certs"
          mount_path = "/certs/client"
          medium = "Memory"
resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m

